# Generated by Django 4.2 on 2023-05-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVacancy', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applyed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendations.students')),
            ],
        ),
    ]
