# Generated by Django 4.2 on 2023-05-28 22:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0004_alter_candidates_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='experience',
            field=models.CharField(default='1 año', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['python'], size=None),
            preserve_default=False,
        ),
    ]
