# Generated by Django 4.2 on 2023-05-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0005_students_experience_students_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mail',
            field=models.CharField(default='paco@uv.edu.co', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='Paco Merte', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default='3332221111', max_length=100),
            preserve_default=False,
        ),
    ]
