# Generated by Django 4.2 on 2023-04-10 01:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keyWords', models.CharField(max_length=500)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(1200000)])),
                ('experience', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.companies')),
                ('idContract', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacantes.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('idVacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacancy')),
            ],
        ),
    ]
