# Generated by Django 4.2 on 2023-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_alter_companies_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='additionalInfo',
            field=models.TextField(default='---'),
            preserve_default=False,
        ),
    ]
