# Generated by Django 4.2 on 2023-05-27 23:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_vacancy_additionalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='keyWords',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='modality',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='place',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
