# Generated by Django 4.2 on 2023-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0004_remove_vacancy_keywords_vacancy_modality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.CharField(default='Mi Empresa', max_length=300),
            preserve_default=False,
        ),
    ]
